### ISSUE TITLE
Bugs e coisas que podem  ser melhoradas

### ISSUE THREAD

**Issue by LuisGomes18** [Vagetti-dev/Five-Night-At-Freddy-s---FAN-GAME-3D---#1]
1. Ao pé da caixa da Puppet tem uma ventilação que e meia bugada para entrar e que a textura da umas bugadas
2. O botão da Puppet e bugado que das vários cliques e não vai
3. O tempo da Puppet  cai para um terço logo tipo devia ser cair aos poucos
4. A luzes já devias estar acesas
5. A portas que e preciso estar perto para entrar  ja que quem gravou disse nao tem portas

E de resto eu nao teste ja que são 2 da manhã e nao quero morrer de infarto 🤣🤣.  Mas estes são alguns  dos bugs ja que ainda e uma demo.

**Comment by DevFalconsz** [comment]
Boa noite. Fala Luis.

Como você pode ter visto esse projeto dentro do git é algo incompleto.
Com a evolução que estou tendo agora tenho mais que 40% do game feito em
mãos e publicado.
Verifique na minha itch.io:
https://vagetti-dev.itch.io/five-night-at-freddys-3d-multiplayer


LuisGomes18 ***@***.***> escreveu no dia sexta, 22/07/2022
à(s) 22:28:
